### ISSUE TITLE
fix: PSQLException when persisting json with Hibernate

### ISSUE THREAD

**Issue by karenc-bq** [awslabs/aws-advanced-jdbc-wrapper#349]
### Describe the bug

Persisting JSON data with the wrapper throws an PSQLException:

```

Caused by: org.postgresql.util.PSQLException: ERROR: column "jsonstring" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 79
  Location: File: parse_target.c, Routine: transformAssignedExpr, Line: 785
  Server SQLState: 42804
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at software.amazon.jdbc.wrapper.PreparedStatementWrapper.lambda$executeUpdate$17(PreparedStatementWrapper.java:253)
	at software.amazon.jdbc.plugin.DefaultConnectionPlugin.execute(DefaultConnectionPlugin.java:98)
	at software.amazon.jdbc.ConnectionPluginManager.lambda$execute$3(ConnectionPluginManager.java:329)
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$0(ConnectionPluginManager.java:269)
	at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:251)
	at software.amazon.jdbc.ConnectionPluginManager.execute(ConnectionPluginManager.java:326)
	at software.amazon.jdbc.util.WrapperUtils.executeWithPlugins(WrapperUtils.java:226)
	at software.amazon.jdbc.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:247)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 20 more
```

### Expected Behavior

No exceptions. Same code works fine with the community Postgres driver.

### What plugins are used? What other connection properties were set?

None

### Current Behavior

PSQLException

### Reproduction Steps

Add the following files to a Java project and run TestJsonHibernate.java.

Disclaimer: since the error was first seen by running the Hibernate ORM test suite, part of the  code snippets below are derived from some of that test code, including `EntityWithJson` and `StringNode`.

### TestJsonHibernate.java
``` java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.cfg.Configuration;
import org.hibernate.type.SqlTypes;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

public class TestJsonHibernate {

  private static final String create = "CREATE TABLE IF NOT EXISTS EntityWithJson\n"
      + "(\n"
      + "    id INTEGER NOT NULL,\n"
      + "    jsonString jsonb,\n"
      + "    list jsonb,\n"
      + "    objectMap jsonb,\n"
      + "    payload jsonb,\n"
      + "    primary key (id)\n"
      + ")";

  public static void main(String[] args) throws SQLException {
    try (Connection connection = DriverManager.getConnection("jdbc:aws-wrapper:postgresql://cluster-domain/db", "user", "pass");
        Statement statement = connection.createStatement()) {
      statement.executeUpdate(create);
    }

    Configuration configuration = new Configuration();
    configuration.configure("hibernate.cfg.xml");
    configuration.addAnnotatedClass(EntityWithJson.class);

    // Create Session Factory
    SessionFactory sessionFactory = configuration.buildSessionFactory();

    // Initialize Session Object
    Session session = sessionFactory.openSession();

    Map<String, String> stringMap = Map.of("name", "ABC");
    Map<StringNode, StringNode> objectMap = Map.of(new StringNode("name"), new StringNode("ABC"));
    List<StringNode> list = List.of(new StringNode("ABC"));
    String json = "{\"name\":\"abc\"}";

    EntityWithJson entity = new EntityWithJson(3, stringMap, objectMap, list, json);

    session.beginTransaction();
    session.persist(entity);
    session.getTransaction().commit();
  }

  @Entity(name = "EntityWithJson")
  @Table(name = "EntityWithJson")
  public static class EntityWithJson {

    @Id
    private Integer id;

    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, String> payload;

    @JdbcTypeCode(SqlTypes.JSON)
    private Map<StringNode, StringNode> objectMap;

    @JdbcTypeCode(SqlTypes.JSON)
    private List<StringNode> list;

    @JdbcTypeCode(SqlTypes.JSON)
    private String jsonString;

    public EntityWithJson() {
    }

    public EntityWithJson(
        Integer id,
        Map<String, String> payload,
        Map<StringNode, StringNode> objectMap,
        List<StringNode> list,
        String jsonString) {
      this.id = id;
      this.payload = payload;
      this.objectMap = objectMap;
      this.list = list;
      this.jsonString = jsonString;
    }
  }

  public static class StringNode {

    private String string;

    public StringNode() {
    }

    public StringNode(String string) {
      this.string = string;
    }

    public String getString() {
      return string;
    }

    public void setString(String string) {
      this.string = string;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }

      StringNode that = (StringNode) o;

      return Objects.equals(string, that.string);
    }

    @Override
    public int hashCode() {
      return string != null ? string.hashCode() : 0;
    }
  }
}

```

### JacksonJsonFormatMapper.java
https://github.com/hibernate/hibernate-orm/blob/2ca0e1042952dbb3f80cecde9af87ddb0bc34cea/hibernate-core/src/main/java/org/hibernate/type/jackson/JacksonJsonFormatMapper.java

### hibernate.config.xml

```xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE hibernate-configuration PUBLIC
  "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
  "http://www.hibernate.org/dtd/hibernate-configuration-3.0.dtd">
<hibernate-configuration>
  <session-factory>
    <property name="hibernate.connection.url">
      <!--      jdbc:postgresql://cluster-domain/db-->
      jdbc:aws-wrapper:postgresql://cluster-domain/db
    </property>
    <property name="hibernate.connection.username">foo</property>
    <property name="hibernate.connection.password">bar</property>
    <property name="hibernate.connection.driver_class">software.amazon.jdbc.Driver</property>
    <!--    <property name="hibernate.connection.driver_class">org.postgresql.Driver</property>-->
    <property name="hibernate.show_sql">true</property>
  </session-factory>
</hibernate-configuration>
```

### The AWS Advanced JDBC Driver version used

1.0.1

### JDK version used

11

### Operating System and version

Windows 11 & Ubuntu

**Comment by karenc-bq** [comment]
This issue is resolved with the latest Hibernate ORM release 6.2.0.CR2
