### ISSUE TITLE
NoClassDefError when connecting to Aurora Postgres

### ISSUE THREAD

**Issue by NikolayMetchev** [awslabs/aws-advanced-jdbc-wrapper#444]
### Describe the bug

Upgrading our code from version 1.0.2 to 2.1.0 results in the exception below.

Here is how we create the connection:

```
        username = creds.username
        password = creds.password
        dataSourceClassName = AwsWrapperDataSource::class.java.name
        addDataSourceProperty("jdbcProtocol", "jdbc:postgresql:")
        addDataSourceProperty("databasePropertyName", "databaseName")
        addDataSourceProperty("portPropertyName", "portNumber")
        addDataSourceProperty("serverPropertyName", "serverName")
        addDataSourceProperty("targetDataSourceClassName", PGSimpleDataSource::class.java.name)
        val targetDataSourceProps = Properties()
        targetDataSourceProps.setProperty("serverName", dbDetails.host.value)
        targetDataSourceProps.setProperty("databaseName", db.name)
        targetDataSourceProps.setProperty("portNumber", dbDetails.port.value.toString())
        targetDataSourceProps.setProperty("wrapperLoggerLevel", "CONFIG")
        targetDataSourceProps.setProperty("wrapperLogUnclosedConnections", "true")
        val plugins = if (dbDetails.isAurora) {
            // https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#list-of-available-plugins
            // TODO: This is where you can enable IAM auth
            "auroraConnectionTracker,failover,efm"
        } else {
            ""
        }
        targetDataSourceProps.setProperty("wrapperPlugins", plugins)
        addDataSourceProperty("targetDataSourceProperties", targetDataSourceProps)
```

### Expected Behavior

Connect to Aurora

### What plugins are used? What other connection properties were set?

"auroraConnectionTracker,failover,efm"

### Current Behavior

java.lang.NoClassDefFoundError: com/mysql/cj/exceptions/WrongArgumentException
	at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.lambda$initHostProvider$0(FailoverConnectionPlugin.java:213) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.initHostProvider(FailoverConnectionPlugin.java:245) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.initHostProvider(FailoverConnectionPlugin.java:209) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$initHostProvider$8(ConnectionPluginManager.java:517) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:278) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:256) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ConnectionPluginManager.initHostProvider(ConnectionPluginManager.java:513) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:128) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:88) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ds.AwsWrapperDataSource.createConnectionWrapper(AwsWrapperDataSource.java:163) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at software.amazon.jdbc.ds.AwsWrapperDataSource.getConnection(AwsWrapperDataSource.java:133) ~[aws-advanced-jdbc-wrapper-2.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at com.paxos.messaging.db.HikariDataSourceFactoryKt.createHikariDatasource-dWUq8MI(HikariDataSourceFactory.kt:214) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.HikariDataSourceFactoryKt.createHikariDatasource-9VgGkz4(HikariDataSourceFactory.kt:139) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.DefaultHikariDataSourceFactory$createHikariDataSource$2.invoke(HikariDataSourceFactory.kt:66) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.DefaultHikariDataSourceFactory$createHikariDataSource$2.invoke(HikariDataSourceFactory.kt:63) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.DefaultHikariDataSourceFactory.createHikariDataSource$lambda$0(HikariDataSourceFactory.kt:63) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.paxos.messaging.db.DefaultHikariDataSourceFactory.createHikariDataSource(HikariDataSourceFactory.kt:63) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.DefaultDataSourceFactory.createDataSource(DefaultDataSourceFactory.kt:12) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.DefaultDbTransactionFactory.createReadOnlyDbTransaction(DefaultDbTransactionFactory.kt:15) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at com.paxos.messaging.db.AbstractDbTransactionFactory$roTx$2.invokeSuspend(AbstractDbTransactionFactory.kt:20) ~[messaging-utils-db-db-impl-1679-d6375b82.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.exceptions.WrongArgumentException
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 35 more

### Reproduction Steps

Upgrade to 2.1.0 
Try to connect to Aurora Postgres

### The AWS Advanced JDBC Driver version used

2.1.0

### JDK version used

17.0.6

### Operating System and version

linux

**Comment by karenc-bq** [comment]
@NikolayMetchev thank you for raising this issue! We are currently working on a fix and we will keep you posted with our updates!

**Comment by karenc-bq** [comment]
Hi @NikolayMetchev, we released version 2.1.1 addressing this issue. We will be closing this issue now, but please don't hesitate to create a new issue if the problem persists. Thank you.
