### ISSUE TITLE
2.2.1 is not Backwards compatible with 2.1.2

### ISSUE THREAD

**Issue by jrobe** [awslabs/aws-advanced-jdbc-wrapper#502]
### Describe the bug

Upon updating my project to use 2.2.1 from 2.1.2; I began getting "java.sql.SQLException: No suitable driver" in my application. 

This is happening even with the simplest ```DriverManager.getConnection("jdbc:aws-wrapper:postgresql:some.server.url/postgres");``` codepaths (and more complex hikari ones). 

The stack for this looks like this:
```: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:?]
	at software.amazon.jdbc.Driver.connect(Driver.java:99) ~[aws-advanced-jdbc-wrapper-2.2.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
```
(Using hikari with driver-based configuration setup). 

I suspected that the TargetDriverDialect changes could have been the cause; so I added 
```
            //props.setProperty(TargetDriverDialectManager.TARGET_DRIVER_DIALECT.name, TargetDriverDialectCodes.PG_JDBC);
```
To my code, but that still didn't get it to work how it did in 2.1.2.

### Expected Behavior

I'd expect the driver manager to be able to know what to use after the AWSWrapper hands it off to the underling DriverManager.

### What plugins are used? What other connection properties were set?

iam; (tested with TargetDriverDialect, pg_jdbc, but didn't work.

### Current Behavior

```
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:?]
	at software.amazon.jdbc.Driver.connect(Driver.java:99) ~[aws-advanced-jdbc-wrapper-2.2.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:?]
```

### Reproduction Steps

Honestly, based on my experience; even the most basic example code pieces given should fail...

### The AWS Advanced JDBC Driver version used

2.2.1

### JDK version used

11.19

### Operating System and version

Centos7

**Comment by jrobe** [comment]
Disregard; must be something else, just repro'd my issue with 2.1.2 - apologies.
