### ISSUE TITLE
Add Driver-Based Hikari Example

### ISSUE THREAD

**Issue by jrobe** [awslabs/aws-advanced-jdbc-wrapper#505]
### Describe the feature

Currently, the examples provided use Datasource based AWSWrapper configuration for Hikari. The ask is for a working & tested example of using Hikari with driver-based configuration; e.g. by setting: dataSource.setDriverClassName("software.amazon.jdbc.Driver");.

### Use Case

Using the AWSWrapper datasource unfortunately messes with the connection properties that get passed around the stack during the connection (specifically the properties that get passed to a custom SSLSocketFactory). My app (admittedly probably could be changed to avoid this) uses custom properties passed to the SSLSocketFactory to setup the trust-store appropriately for the connection.

Ideally, instead of the AWSWrapperDataSource, we would be able to use Hikari using driver-based configuration (e.g. setting dataSource.setDriverClassName("software.amazon.jdbc.Driver")). I've been able to do this and unit test it (and it works with unit-testing); however I'm running into issues with Hibernate & "Driver could not be found" exceptions when my actual application runs the code. 

### Other Information

I'm wondering if I'm missing something, of if there's a bug with Hikari Driver-based configuration right now. 

The stack trace for this problem (using Driver-based hikari) is as follows:
```
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.25.jar:5.3.25]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71) ~[spring-aspects-5.3.25.jar:5.3.25]
	at [redacted]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167) ~[aspectjrt-1.9.5.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167) ~[aspectjrt-1.9.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:516) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:152) ~[spring-orm-5.3.25.jar:5.3.25]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.25.jar:5.3.25]
	... 26 more
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:?]
	at software.amazon.jdbc.Driver.connect(Driver.java:99) ~[aws-advanced-jdbc-wrapper-2.2.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:?]
	at org.springframework.jdbc.datasource.DelegatingDataSource.getConnection(DelegatingDataSource.java:99) ~[spring-jdbc-5.3.25.jar:5.3.25]
[redacted]
	at org.springframework.jdbc.datasource.DelegatingDataSource.getConnection(DelegatingDataSource.java:99) ~[spring-jdbc-5.3.25.jar:5.3.25]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:516) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:152) ~[spring-orm-5.3.25.jar:5.3.25]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.25.jar:5.3.25]
	... 26 more
```

The above exception does not occur using the AWSWrapper Datasource.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.2.1

### JDK version used

11.19

### Operating System and version

Centos7

**Comment by jrobe** [comment]
My Hikari setup code (not exact, modified to make generic)

```
public DataSource getDataSource(){
        DataSource dataSource = new HikariDataSource();
        dataSource.setDriverClassName("software.amazon.jdbc.Driver");
        dataSource.addDataSourceProperty("jdbcProtocol", "jdbc:postgresql:");
        dataSource.addDataSourceProperty(PropertyDefinition.PLUGINS.name, "iam");
        dataSource.addDataSourceProperty(TargetDriverDialectManager.TARGET_DRIVER_DIALECT.name, TargetDriverDialectCodes.PG_JDBC);
        dataSource.addDataSourceProperty(DialectManager.DIALECT.name, DialectCodes.RDS_PG);
        dataSource.addDataSourceProperty("serverName", m_targetHost);
        dataSource.addDataSourceProperty("database", m_dbName);
        dataSource.addDataSourceProperty("serverPort", m_targetPort.toString());
        dataSource.setJdbcUrl(m_connectionString);
        dataSource.setDataSourceProperties(m_commonConnectionInfo.getProperties());
        dataSource.setUsername(someUserName);
        dataSource.setMaximumPoolSize(somePoolSize);
        dataSource.setMinimumIdle(someIdleSize);
        dataSource.setIdleTimeout(someIdleTimeout);
        dataSource.setConnectionTimeout(someConnectionTimeout);
        dataSource.setLeakDetectionThreshold(LEAK_THRESHOLD_MS);
        dataSource.setPoolName(somePoolName);
        dataSource.setRegisterMbeans(true);
        return dataSource;
}
```

**Comment by karenc-bq** [comment]
Hi @jrobe, thank you for the suggestion.

`Driver could not be found` is thrown when the target driver cannot be found on the classpath. Could you please verify if the [PostgreSQL JDBC driver](https://github.com/pgjdbc/pgjdbc) has been loaded onto the classpath?
```
dependencies {
    implementation("org.postgresql:postgresql:42.5.4")
    implementation("software.amazon.awssdk:rds:2.20.49")
    implementation("software.amazon.jdbc:aws-advanced-jdbc-wrapper:2.2.1")
}
```

Meanwhile, here is a simple example:

```java

try (HikariDataSource ds = new HikariDataSource()) {

      // Configure the connection pool:
      ds.setUsername("user");
      ds.setPassword("pass");

      ds.setDriverClassName("software.amazon.jdbc.Driver");
      ds.setJdbcUrl("jdbc:aws-wrapper:postgresql://database.cluster-xyz.us-east-2.rds.amazonaws.com/");

      ds.addDataSourceProperty(PropertyDefinition.PLUGINS.name, "iam");
      ds.addDataSourceProperty("database", "postgres");

      try (final Connection conn = ds.getConnection();
          final Statement statement = conn.createStatement();
          final ResultSet rs = statement.executeQuery("SELECT * from aurora_db_instance_identifier()")) {
        while (rs.next()) {
          System.out.println(rs.getString(1));
        }
      }
    }

```

**Comment by jrobe** [comment]
Thanks so much for the quick response; I verified that implementation("org.postgresql:postgresql:42.5.4") was included in the dependencies and that it was on the classpath.

Note the above example you posted works for me on unit tests; but is throwing the exception when Hibernate gets in the mix (see the stack trace). I'm only getting the error with Driver-based Hikari on that Hibernate-using code path.

**Comment by jrobe** [comment]
I also tried using the plugin to use the Driver Metadata Connection [Plugin](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheDriverMetadataConnectionPlugin.md) - but that didn't have any impact.

**Comment by jrobe** [comment]
Feel free to close this is needed; but I am curious why the AwsWrapperDataSource with Hikari doesn't run into this, but the driver based (as implemented above) hits the "No Suitable Driver" issue.

**Comment by karenc-bq** [comment]
Could you please modify your `getDatasource()` method to the following:
```java
  public DataSource getDataSource(){
    DataSource dataSource = new HikariDataSource();
    dataSource.setDriverClassName("software.amazon.jdbc.Driver");
    dataSource.addDataSourceProperty(PropertyDefinition.PLUGINS.name, "iam");
    dataSource.setJdbcUrl("jdbc:aws-wrapper:postgresql://rds-proxy-endpoint.rds.amazonaws.com/postgres");
    dataSource.setDataSourceProperties(m_commonConnectionInfo.getProperties());
    dataSource.setUsername(someUserName);
    dataSource.setMaximumPoolSize(somePoolSize);
    dataSource.setMinimumIdle(someIdleSize);
    dataSource.setIdleTimeout(someIdleTimeout);
    dataSource.setConnectionTimeout(someConnectionTimeout);
    dataSource.setLeakDetectionThreshold(LEAK_THRESHOLD_MS);
    dataSource.setPoolName(somePoolName);
    dataSource.setRegisterMbeans(true);
    return dataSource;
  }
```

Could you also enable driver logging? [Here is an example on how you could do it through yaml](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/6a7afbcab4dc7d81c047c43c3f0ff157d11da0b5/examples/SpringHibernateExample/src/main/resources/application.yml#L19).

**Comment by jrobe** [comment]
Attempting this, but still getting errors with the same stack trace as mentioned before.

I'm trying to grab the logs, but my application has logging setup a bit differently, so they're getting hidden & are hard to find. I'll post them when I track them down.

**Comment by jrobe** [comment]
Unfortunately, this is the only log output I'm getting: 
```
TRACE software.amazon.jdbc.Driver - Opening connection to jdbc:aws-wrapper:postgresql://proxy.proxy.us-west-2.rds.amazonaws.com:5432/postgres?ssl=true&sslmode=verify-full&sslfactory=[redacted from github]
```
Followed shortly after by the exception stack trace (with the root exception being):
```
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:?]
	at software.amazon.jdbc.Driver.connect(Driver.java:99) ~[aws-advanced-jdbc-wrapper-2.2.1.jar:?]
```

I'm going to close this for now because I wasn't able to provide enough context; and I'll just use AwsWrapperDatasource instead.

**Comment by karenc-bq** [comment]
Hi @jrobe, we improved the messaging for `no suitable driver`. If you are still interested in using the DriverManager, would you be able to try out the latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) to help us resolve this issue?

**Comment by jrobe** [comment]
Thanks! I'll give it a shot when I get some free time. It ended up indeed being a very strange class-path issue (unsure of why, didn't have enough time to fully investigate it); but I had to just add the following block to my code before making the Hikari Datasource, and then things started working as expected. I have no idea why the driver stopped being loaded like it must have been previously.

```java
if (!org.postgresql.Driver.isRegistered()) {
   try {
        org.postgresql.Driver.register()
   } catch (Exception ex) {
        LOGGER.error("Error registereding postgres driver");
   }
}
```

**Comment by karenc-bq** [comment]
Thank you, that is very helpful information!
