### ISSUE TITLE
Driver based spring orm with tomcat jdbc pool configuration not working(short issue description)

### ISSUE THREAD

**Issue by rakshith-agi** [awslabs/aws-advanced-jdbc-wrapper#541]
### Describe the bug

We are using spring orm with tomcat jdbc pool configuration to create database connection. But getting "java.sql.SQLException: No suitable driver" exception.

### Expected Behavior

DB transaction should be successful

### What plugins are used? What other connection properties were set?

NA

### Current Behavior

java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at software.amazon.jdbc.Driver.connect(Driver.java:97)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:194)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:138)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:225)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:809)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:261)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:773)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:330)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:519)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:734)
	at com.sun.proxy.$Proxy288.createEntityManager(Unknown Source)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:305)
	at com.sun.proxy.$Proxy292.createNativeQuery(Unknown Source)

### Reproduction Steps

Dependency :
<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.6.0</version>
        </dependency>
        <dependency>
        	<groupId>software.amazon.jdbc</groupId>
        	<artifactId>aws-advanced-jdbc-wrapper</artifactId>
        	<version>2.1.2</version>
   		 </dependency>

Srping JPA bean xml :

	<bean id="transactionManager" class="org.springframework.orm.jpa.JpaTransactionManager">
        <property name="entityManagerFactory" ref="entityManager"/>
    </bean>

    <bean name="entityManager"
          class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
        <property name="persistenceXmlLocation" value="classpath:META-INF/persistence.xml"/>
        <property name="persistenceUnitName" value="pum"/>
        <property name="dataSource" ref="mainDataSource"/>
        <property name="jpaVendorAdapter">
            <bean class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter"/>
        </property>
    </bean>

    <bean id="parentDataSource" class="org.apache.tomcat.jdbc.pool.DataSource" destroy-method="close" abstract="true">
        <property name="maxActive" value="${hikari_maximumPoolSize}"/>
        <property name="minIdle" value="${APP_MIN_IDLE_SIZE}"/>
        <property name="maxIdle" value="${APP_MAX_IDLE_SIZE}"/>
        <property name="initialSize" value="${APP_INIT_POOL_SIZE}"/>
        <property name="timeBetweenEvictionRunsMillis" value="${APP_EVICTION_RUN_INTERVAL}"/>
        <property name="minEvictableIdleTimeMillis" value="${APP_EVICTION_IDLE_TIME}"/>
        <property name="maxWait" value="${MAXWAIT}"/>
        <property name="removeAbandoned" value="${REMOVEABANDONED}"/>
        <property name="removeAbandonedTimeout" value="${REMOVEABANDONEDTIMEOUT}"/>
        <property name="logAbandoned" value="${LOGABANDONED}"/>
        <property name="abandonWhenPercentageFull" value="${ABANDONWHENPERCENTAGEFULL}"/>
        <property name="maxAge" value="${MAXAGE}"/>
        <property name="alternateUsernameAllowed" value="${ALTERNATEUSERNAMEALLOWED}"/>
        <property name="jdbcInterceptors" value="${JDBCINTERCEPTORS}"/>
        <property name="jmxEnabled" value="${JMXENABLED}"/>
       	<property name="validationQuery" value="${test.validate.query}"/>
        <property name="testWhileIdle" value="${test.while.idle}"/>
    </bean>

    <bean id="mainDataSource"
          class="com.test.RoutingDataSource">
        <property name="targetDataSources">
            <map key-type="java.lang.String">
                <entry key="MAIN_DS" value-ref="DS_DEV"/>
            </map>
        </property>
    </bean>

    <bean id="exporter" class="org.springframework.jmx.export.MBeanExporter" depends-on="DS_DEV">
        <property name="autodetect" value="true"/>
        <property name="registrationPolicy" value="IGNORE_EXISTING" />
    </bean>

	<bean id="DS_DEV" parent="parentDataSource">
        <property name="driverClassName" value="${db_driver}"/>
        <property name="url" value="${db_url}"/>
        <property name="username" value="${db_userName}"/>
        <property name="password" value="${db_password}"/>
    </bean>

Catalina.properties :
	
db_driver=software.amazon.jdbc.Driver
db_url=jdbc:aws-wrapper:postgresql://localhost:5433/test
db_userName=<username>
db_password=<password>
SCHD_MIN_IDLE_SIZE=2
SCHD_MAX_IDLE_SIZE=2
APP_MIN_IDLE_SIZE=2
APP_MAX_IDLE_SIZE=2
SCHD_INIT_POOL_SIZE=2
APP_INIT_POOL_SIZE=2
SCHD_EVICTION_RUN_INTERVAL=300000
SCHD_EVICTION_IDLE_TIME=60000
APP_EVICTION_RUN_INTERVAL=300000
APP_EVICTION_IDLE_TIME=60000
MAXWAIT=30000
REMOVEABANDONED=FALSE
REMOVEABANDONEDTIMEOUT=60000
LOGABANDONED=FALSE
ABANDONWHENPERCENTAGEFULL=0
MAXAGE=0
ALTERNATEUSERNAMEALLOWED=FALSE
JDBCINTERCEPTORS=StatementCache(prepared=true, callable=true, max=1000);StatementDecoratorInterceptor;
JSON_PATH=C:/3656/Temp/json
JMXENABLED=false

#POSTGRE
test.validate.query=select 1
test.while.idle=false
	

### The AWS Advanced JDBC Driver version used

2.1.2

### JDK version used

1.8.0_241

### Operating System and version

windows 10

**Comment by crystall-bitquill** [comment]
Hi @rakshith-agi,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

In the meantime, could you please provide driver logs, which can be enabled as seen [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging)? Additionally, it seems like your dependencies include the PostgreSQL JDBC Driver, could you please verify that it is on the classpath?

Thank you!

**Comment by jrobe** [comment]
I had the same issue! I ended up having to manually load the driver to get it to work. I don't know why I had to do that. Here's what I added that fixed it:

```java
if (!org.postgresql.Driver.isRegistered()) {
   try {
        org.postgresql.Driver.register()
   } catch (Exception ex) {
        LOGGER.error("Error registereding postgres driver");
   }
}
```

**Comment by rakshith-agi** [comment]
Hi @crystall-bitquill , Sorry for late response. Yes, Postgres JDBC driver is in classpath. Application works fine with postgresql driver.

**Comment by rakshith-agi** [comment]
Hi @jrobe, Thanks, I will check this.

**Comment by karenc-bq** [comment]
Hi @rakshith-agi, are you still experiencing the issue after manually registering the driver?

**Comment by crystall-bitquill** [comment]
Hi @rakshith-agi,

I wanted to check in and see if the issue was resolved.

If there are no further updates on this ticket in the next few days, we will close this ticket. However, if you have any further questions or concerns please feel free to reopen this issue, or create a new one.

Thank you!
