### ISSUE TITLE
Unable to use reader endpoint to connect

### ISSUE THREAD

**Issue by lily-es** [awslabs/aws-advanced-jdbc-wrapper#593]
### Describe the bug

Attempting to create a data pool using the reader endpoint (`XXXXXXXX.cluster-ro-XXXXXX.eu-north-1.rds.amazonaws.com`) using Hikari fails. This does not happen when using the writer endpoint(`XXXXXXXX.cluster-XXXXXX.eu-north-1.rds.amazonaws.com`).

### Expected Behavior

Connection to succeed just like when using the writer endpoint.

### What plugins are used? What other connection properties were set?

auroraConnectionTracker,failover,efm,iam

### Current Behavior

This exception is thrown

    12:10:50.628 ERROR | com.zaxxer.hikari.pool.PoolBase - backend - Failed to execute isValid() for connection, configure connection test query (java.lang.RuntimeException: Unable to identify the given connection: 'xxxxxxxxx.cluster-ro-xxxxxxxxx.eu-north-1.rds.amazonaws.com', please ensure the correct host list provider is specified. The host list provider in use is: 'software.amazon.jdbc.hostlistprovider.AuroraHostListProvider@60297f36'.). traceId=
    12:10:50.637 ERROR | com.zaxxer.hikari.pool.HikariPool - backend - Error thrown while acquiring connection from data source traceId=
    java.sql.SQLException: java.lang.RuntimeException: Unable to identify the given connection: 'xxxxxxxxx.cluster-ro-xxxxxxxxx.eu-north-1.rds.amazonaws.com', please ensure the correct host list provider is specified. The host list provider in use is: 'software.amazon.jdbc.hostlistprovider.AuroraHostListProvider@60297f36'.
	    at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	    at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	    at software.amazon.jdbc.util.WrapperUtils.createInstance(WrapperUtils.java:444) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.util.WrapperUtils.wrapExceptionIfNeeded(WrapperUtils.java:562) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.dealWithOriginalException(FailoverConnectionPlugin.java:536) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:200) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$execute$3(ConnectionPluginManager.java:340) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:283) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:283) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.execute(AuroraConnectionTrackerPlugin.java:123) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$execute$3(ConnectionPluginManager.java:340) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:283) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:261) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.execute(ConnectionPluginManager.java:337) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.util.WrapperUtils.executeWithPlugins(WrapperUtils.java:219) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.wrapper.ConnectionWrapper.isValid(ConnectionWrapper.java:484) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at com.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:459) ~[HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442) ~[HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:411) ~[HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) [HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) [HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) [HikariCP-5.0.1.jar:?]
	    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) [HikariCP-5.0.1.jar:?]
    Caused by: java.lang.RuntimeException: Unable to identify the given connection: 'xxxxxxxxx.cluster-ro-xxxxxxxxx.eu-north-1.rds.amazonaws.com', please ensure the correct host list provider is specified. The host list provider in use is: 'software.amazon.jdbc.hostlistprovider.AuroraHostListProvider@60297f36'.
	    at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.getMonitoringHostSpec(HostMonitoringConnectionPlugin.java:314) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.execute(HostMonitoringConnectionPlugin.java:170) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$execute$3(ConnectionPluginManager.java:340) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:283) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:283) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:196) ~[aws-advanced-jdbc-wrapper-2.2.3.jar:?]
	    ... 22 more

### Reproduction Steps

       val config = HikariConfig()
        val dbEndpoint = "RO endpoint here"
        val dbPort = "db port here"
        val databaseName = "db name here"

        // Standard config
        config.poolName = databaseName
        config.isReadOnly = false
        config.isAutoCommit = true
        config.maximumPoolSize = 4
        config.minimumIdle = 1
        config.connectionTimeout = 3000

        // Aws driver config.
        // Example: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java
        config.dataSourceClassName = AwsWrapperDataSource::class.java.name
        config.exceptionOverrideClassName = HikariCPSQLException::class.java.name
        config.addDataSourceProperty("jdbcProtocol", "jdbc:postgresql:")
        config.addDataSourceProperty("serverName", dbEndpoint)
        config.addDataSourceProperty("database", databaseName)
        config.addDataSourceProperty("serverPort", dbPort)
        config.addDataSourceProperty("targetDataSourceClassName", PGSimpleDataSource::class.java.name)

        val targetDataSourceProps = Properties()
        targetDataSourceProps.setProperty("wrapperPlugins", "auroraConnectionTracker,failover,efm,iam")

        config.addDataSourceProperty("targetDataSourceProperties", targetDataSourceProps)

        HikariDataSource(config)

### Additional Information/Context

I'm using Kotlin, although that probably doesnt matter.

### The AWS Advanced JDBC Driver version used

2.2.3

### JDK version used

jdk-20.0.2+9

### Operating System and version

Linux. Specific docker base image is eclipse-temurin:20-jre-jammy

**Comment by crystall-bitquill** [comment]
Hi @lily-es,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @lily-es,

We've recently merged in a fix. Could you kindly check out our [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue persists?

Thank you!

**Comment by lily-es** [comment]
Attempted to connect to **writer** endpoint using aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar
`

10:15:13.698 ERROR \| com.zaxxer.hikari.pool.HikariPool - backend - Exception during pool initialization. traceId=
--
org.postgresql.util.PSQLException: Connection attempt timed out.
at org.postgresql.Driver$ConnectThread.getResult(Driver.java:407) ~[postgresql-42.6.0.jar:42.6.0]
at org.postgresql.Driver.connect(Driver.java:304) ~[postgresql-42.6.0.jar:42.6.0]
at java.sql.DriverManager.getConnection(Unknown Source) ~[java.sql:?]
at java.sql.DriverManager.getConnection(Unknown Source) ~[java.sql:?]
at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103) ~[postgresql-42.6.0.jar:42.6.0]
at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87) ~[postgresql-42.6.0.jar:42.6.0]
at software.amazon.jdbc.DataSourceConnectionProvider.connect(DataSourceConnectionProvider.java:146) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:155) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:148) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$0(ConnectionPluginManager.java:182) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:151) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:96) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.connectInternal(HostMonitoringConnectionPlugin.java:279) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.connect(HostMonitoringConnectionPlugin.java:274) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.staledns.AuroraStaleDnsHelper.getVerifiedConnection(AuroraStaleDnsHelper.java:65) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connectInternal(FailoverConnectionPlugin.java:727) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connect(FailoverConnectionPlugin.java:720) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connectInternal(AuroraConnectionTrackerPlugin.java:90) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connect(AuroraConnectionTrackerPlugin.java:83) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:164) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:278) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:139) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:90) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ds.AwsWrapperDataSource.createConnectionWrapper(AwsWrapperDataSource.java:201) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at software.amazon.jdbc.ds.AwsWrapperDataSource.getConnection(AwsWrapperDataSource.java:171) ~[aws-advanced-jdbc-wrapper-2.2.4-20230819.003026-46.jar:?]
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) [HikariCP-5.0.1.jar:?]
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) [HikariCP-5.0.1.jar:?]
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) [HikariCP-5.0.1.jar:?]
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) [HikariCP-5.0.1.jar:?]
at systems.oslo.citykey.monitor.db.DatabaseConfig.createPoolForDatabase(DatabaseConfig.kt:49) [monitor-db-1.0.0-SNAPSHOT.jar:?]
at systems.oslo.citykey.monitor.server.MonitorServerLifecycle.<init>(MonitorServerLifecycle.kt:49) [classes/:?]
at systems.oslo.citykey.monitor.server.MonitorServerBootstrapper.main(MonitorServerBootstrapper.kt:200) [classes/:?]
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Connection attempt timed out.
at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
at systems.oslo.citykey.monitor.db.DatabaseConfig.createPoolForDatabase(DatabaseConfig.kt:49)
at systems.oslo.citykey.monitor.server.MonitorServerLifecycle.<init>(MonitorServerLifecycle.kt:49)
at systems.oslo.citykey.monitor.server.MonitorServerBootstrapper.main(MonitorServerBootstrapper.kt:200)
Caused by: org.postgresql.util.PSQLException: Connection attempt timed out.
at org.postgresql.Driver$ConnectThread.getResult(Driver.java:407)
at org.postgresql.Driver.connect(Driver.java:304)
at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
at software.amazon.jdbc.DataSourceConnectionProvider.connect(DataSourceConnectionProvider.java:146)
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:155)
at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:148)
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281)
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$0(ConnectionPluginManager.java:182)
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186)
at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:151)
at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:96)
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281)
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186)
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186)
at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.connectInternal(HostMonitoringConnectionPlugin.java:279)
at software.amazon.jdbc.plugin.efm.HostMonitoringConnectionPlugin.connect(HostMonitoringConnectionPlugin.java:274)
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281)
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186)
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186)
at software.amazon.jdbc.plugin.staledns.AuroraStaleDnsHelper.getVerifiedConnection(AuroraStaleDnsHelper.java:65)
at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connectInternal(FailoverConnectionPlugin.java:727)
at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connect(FailoverConnectionPlugin.java:720)
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281)
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186)
at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:186)
at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connectInternal(AuroraConnectionTrackerPlugin.java:90)
at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connect(AuroraConnectionTrackerPlugin.java:83)
at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:281)
at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:186)
at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:164)
at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:278)
at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:139)
at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:90)
at software.amazon.jdbc.ds.AwsWrapperDataSource.createConnectionWrapper(AwsWrapperDataSource.java:201)
at software.amazon.jdbc.ds.AwsWrapperDataSource.getConnection(AwsWrapperDataSource.java:171)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
... 5 more

`

**Comment by lily-es** [comment]
Hmm it started working on the 5th attempt.. Might have been some instability with RDS? Unsure. Will try with the reader endpoint now

**Comment by lily-es** [comment]
Tried with the reader endpoint, kept timing out. Reverted back to 2.2.3 with the writer endpoint getting no timeouts. I think theres something wrong with the snapshot driver that keeps making it timeout.

**Comment by crystall-bitquill** [comment]
Hi @lily-es,

Thanks for letting us know about this issue with the snapshot build.

Unfortunately, we haven't been able to reproduce this problem yet. Would you be able to provide driver logs from using the snapshot build? Logging can be enabled as seen [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging).

And to confirm, what version of Aurora PostgreSQL are you using?

Thank you!

**Comment by lily-es** [comment]
Hello! What logger level should I use?

**Comment by crystall-bitquill** [comment]
Hello, please use the `ALL` logger level, thank you!

**Comment by lily-es** [comment]
Ah, and I am using Aurora PostgreSQL version 15.3

**Comment by crystall-bitquill** [comment]
Hi @lily-es,

Thanks for the update! We aren't aware of any changes that would have increased the time to get a connection. Perhaps it was momentary instability, or issues with your network speed?

If keeping the timeout at a higher value is acceptable to you and the fix resolves the original problem, we'll close this issue for now and keep an eye out for any similar time out errors. If you have any further questions or concerns, please feel free to reopen this issue or to create a new one.

Thank you!
