### ISSUE TITLE
The topology query returned an invalid topology - no writer instance detected.

### ISSUE THREAD

**Issue by Budnic** [awslabs/aws-advanced-jdbc-wrapper#648]
### Describe the bug

Suddenly I started getting an invalid topology error. I can no longer connect to the instance. 
I restarted the machine several times but always the same error. We are using Aurora Serverless V2, MySql 

2023-09-21 03:47:08.920 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:18.973 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:28.511 [pool-2-thread-1] INFO  c.s.d.r.cache.impl.InMemoryCache.removeExpiredItems:198 - Cache: Size=0
2023-09-21 03:47:29.010 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] WARN  o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:127 - SQL Error: 0, SQLState: 
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:129 - HikariPool-1 - Connection is not available, request timed out after 30000ms.
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] WARN  o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:127 - SQL Error: 0, SQLState: 
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:129 - Initial connection isnt open.

### Expected Behavior

To connects normally to the Aurora cluster. 

### What plugins are used? What other connection properties were set?

auroraConnectionTracker,failover,efm

### Current Behavior

023-09-21 03:47:08.920 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:18.973 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:28.511 [pool-2-thread-1] INFO  c.s.d.r.cache.impl.InMemoryCache.removeExpiredItems:198 - Cache: Size=0
2023-09-21 03:47:29.010 [HikariPool-1 connection adder] ERROR s.a.j.h.RdsHostListProvider.processQueryResults:398 - The topology query returned an invalid topology - no writer instance detected.
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] WARN  o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:127 - SQL Error: 0, SQLState: 
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:129 - HikariPool-1 - Connection is not available, request timed out after 30000ms.
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] WARN  o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:127 - SQL Error: 0, SQLState: 
2023-09-21 03:47:38.522 [SS-EXECUTOR-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions:129 - Initial connection isnt open.
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:90)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1929)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2617)
	at org.hibernate.loader.Loader.doList(Loader.java:2600)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
	at org.hibernate.loader.Loader.list(Loader.java:2424)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:372)
	at com.sun.proxy.$Proxy106.getResultList(Unknown Source)
	... 16 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:87)
	... 48 common frames omitted
Caused by: java.sql.SQLException: Initial connection isnt open.
	at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:143)
	at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:90)
	at software.amazon.jdbc.Driver.connect(Driver.java:148)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	... 4 common frames omitted

### Reproduction Steps

Suddenly it started happening on our cluster and we can't connect anymore

### The AWS Advanced JDBC Driver version used

2.2.4

### JDK version used

1.8

### Operating System and version

Ubuntu

**Comment by Budnic** [comment]
I've tried older version with mysql-connector-j, and it connects successfully

**Comment by crystall-bitquill** [comment]
Hi @Budnic,

Thanks for reaching out and raising this issue.

We'll keep you updated as we investigate.

In the meantime, I have a few questions:
- How is your cluster structured? Is it a single writer?
- Were there any changes in the cluster topology? For example, failover or instances being added/removed.
- How is your Hikari pool configured?
- What version of MySQL are you using?

Thank you for your patience!

**Comment by Budnic** [comment]
Hi,

- I'd say she's just a single writer
![test-cluster](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/33682623/372180b3-7fb9-472c-85b7-b4a6ce4e9f5c)
- Only that I noticed in the logs is Seemless scaling happened
- MySql 5.7
- Hikari config:

    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperPlugins: auroraConnectionTracker,failover,efm
        wrapperDialect: aurora-mysql
      target-data-source-class-name: com.mysql.cj.jdbc.MysqlDataSource
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
      max-lifetime: 840000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 120000

**Comment by Budnic** [comment]
SELECT SERVER_ID, CASE WHEN SESSION_ID = 'MASTER_SESSION_ID' THEN TRUE ELSE FALSE END, CPU, REPLICA_LAG_IN_MILLISECONDS, LAST_UPDATE_TIMESTAMP FROM information_schema.replica_host_status WHERE time_to_sec(timediff(now(), LAST_UPDATE_TIMESTAMP)) <= 300 OR SESSION_ID = 'MASTER_SESSION_ID';

I ran this query on my database and got the following result. Maybe this query should be revised?

![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/33682623/1c6eb2ba-818b-4bca-9f5d-4dc3024834f0)

**Comment by crystall-bitquill** [comment]
Hi @Budnic,

Thanks for your quick response!

To confirm, are you using Aurora Serverless v1 or v2? From my understanding, Aurora MySQL 5.7 only has Serverless v1 as an option. Additionally, Aurora Serverless v1 instances will have the role set to "Serverless", like the instance in your screenshot. Aurora Serverless v1 clusters do not use the notion of database instances and therefore will not have a writer or readers.

To use the failover plugin, you will need a provisioned cluster or an Aurora Serverless v2 cluster. The cluster format to use the failover plugin should look something like the image below, with individual writer and reader instances.

![Cluster-Screenshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/97126568/c523e2fa-8e69-4531-b8af-ba18a6fe2f9b)

**Comment by Budnic** [comment]
Hi @crystall-bitquill,

Thank you for you response. 

As far as I know we use Aurora V2

Engine version
5.7.mysql_aurora.2.11.3

![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/33682623/8b9f6c6a-8f3b-49b4-b035-bd904cd2b2fa)

**Comment by crystall-bitquill** [comment]
Hi @Budnic,

Yes, that is the engine version, but outside of the engine there are also two versions of Aurora Serverless: v1 and v2. Some of their differences can be found [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.upgrade.html#aurora-serverless.comparison). 

When creating a database on the RDS console, you can select the Aurora MySQL version, but after selecting the engine version, you can also select instance configuration options. This includes whether the cluster should be provisioned or serverless. In the screenshot below, the only Serverless version available for for Aurora (MySQL 5.7) 2.11.3 is Serverless v1.

<img width="778" alt="648-2" src="https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/97126568/7ff7c620-135d-4478-bdf4-1a7caca2da4b">

This cluster uses Aurora (MySQL 5.7) 2.11.3 and is provisioned (the memory optimized classes option was selected):

![648-4](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/97126568/c9c3d841-1316-4c02-a65f-003b7595ea16)

This cluster uses Aurora (MySQL 5.7) 2.11.3 and Serverless v1:

![648-3](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/97126568/ff0471ba-1d68-45f4-920f-76d9be3a7b98)

The reason I ask what Serverless version is being used is that Serverless v1 clusters do not have writer or reader instances, which will would lead to the topology query not finding a writer, and the image and description of your cluster matches that of the Serverless v1 cluster.

> * I'd say it's just a single writer
>   ![test-cluster](https://user-images.githubusercontent.com/33682623/269840392-372180b3-7fb9-472c-85b7-b4a6ce4e9f5c.png)

**Comment by Budnic** [comment]
Hi @crystall-bitquill,

Thank you for the detailed explanation.

Is there an adapter that supports version 1?
Could you suggest how to overcome this problem? 

If there is no plan to support Aurora V1, you can close this bug.

Best regards,
Spasoje

**Comment by crystall-bitquill** [comment]
Hi @Budnic,

I am not aware of any adapters that support Aurora Serverless v1 failover. If the concern is with failover time, please note that failover with Aurora Serverless v1 clusters will take longer than with Aurora clusters with provisioned or Aurora Serverless v2 instances, as noted [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v1.how-it-works.html#aurora-serverless.failover).

Unfortunately we cannot support Aurora Serverless v1 due to the cluster structure being a single database instance.
