### ISSUE TITLE
Getting a PAM Error When Trying to Connect to Aurora PostgreSQL

### ISSUE THREAD

**Issue by bdudra** [awslabs/aws-advanced-jdbc-wrapper#908]
### Describe the bug

Greetings,

I am still receiving a PAM authentication error when I configuring my application using the examples provided in this repository. 

I validated that my AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY variables are set in my environment to allow the RDS module to connect to the AWS api.

At this point I'm not sure what I'm doing wrong.

Additionally, when I deploy this application in EKS I'm curious if I will need to configure a custom bean in order to use the WebIdentityTokenCredentialProvider in the DefaultCredentialsProviderChain.  It seems like that particular Credential Provider does not take into account the AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN provided to the container by EKS when using the default IAM roles for pods methodology.

### Expected Behavior

I expect the HikariCP Pool to connect to the database.

### What plugins are used? What other connection properties were set?

spring.datasource.url=jdbc:aws-wrapper:postgresql://{DBName}.{CLUSTER_ID}.{REGION}.rds.amazonaws.com:5432/ih?currentSchema=batch&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require spring.datasource.username=batch_user spring.datasource.hikari.data-source-properties.wrapperPlugins: failover,efm2,iam spring.datasource.hikari.data-source-properties.wrapperDialect: aurora-pg spring.datasource.hikari.exception-override-class-name=software.amazon.jdbc.util.HikariCPSQLException

### Current Behavior

`Caused by: org.postgresql.util.PSQLException: FATAL: PAM authentication failed for user "batch_user"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:698) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.Driver.connect(Driver.java:298) ~[postgresql-42.7.2.jar:42.7.2]
	at software.amazon.jdbc.DriverConnectionProvider.connect(DriverConnectionProvider.java:125) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:203) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:191) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:362) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$0(ConnectionPluginManager.java:256) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$1(ConnectionPluginManager.java:256) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:261) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connectInternal(IamAuthConnectionPlugin.java:166) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.IamAuthConnectionPlugin.connect(IamAuthConnectionPlugin.java:110) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:362) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:261) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.efm2.HostMonitoringConnectionPlugin.connectInternal(HostMonitoringConnectionPlugin.java:234) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.efm2.HostMonitoringConnectionPlugin.connect(HostMonitoringConnectionPlugin.java:229) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:362) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:261) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.staledns.AuroraStaleDnsHelper.getVerifiedConnection(AuroraStaleDnsHelper.java:72) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connectInternal(FailoverConnectionPlugin.java:783) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connect(FailoverConnectionPlugin.java:776) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:362) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:260) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:223) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:359) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:160) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:105) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at software.amazon.jdbc.Driver.connect(Driver.java:176) ~[aws-advanced-jdbc-wrapper-2.3.3.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-5.0.1.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160) ~[spring-jdbc-6.1.3.jar:6.1.3]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118) ~[spring-jdbc-6.1.3.jar:6.1.3]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-6.1.3.jar:6.1.3]`

### Reproduction Steps

build.gradle
`implementation group: 'software.amazon.jdbc', name: 'aws-advanced-jdbc-wrapper', version: '2.3.3'
    implementation group: 'software.amazon.awssdk', name: 'sts', version: '2.24.7'
    implementation group: 'software.amazon.awssdk', name: 'rds', version: '2.24.7'`

IAM Policy
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "rds-db:connect",
            "Resource": [
                "arn:aws:rds-db:{REGION}:{ACCOUNT}:dbuser:{CLUSTER_ID}/batch_user"
            ],
            "Effect": "Allow"
        }
    ]
}`

db role
`create role batch_user login
grant connect on database postgres to batch_user
grant rds_iam to batch_use`

### The AWS Advanced JDBC Driver version used

2.3.3

### JDK version used

semeru 17.0.8

### Operating System and version

macOS Sonoma 14.3.1

**Comment by karenc-bq** [comment]
Hi @bdudra, thank you for reaching out. Could you please provide the following information to help us investigate this issue?

Could you please [enable driver logging](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging) and send us the logs? 
Here is a a sample logging.properties file:
```
.level=INFO
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=ALL
software.amazon.jdbc.Driver.level=FINER
software.amazon.jdbc.plugin.level=FINER
software.amazon.jdbc.DriverConnectionProvider.level=FINEST
software.amazon.jdbc.DataSourceConnectionProvider.level=FINEST
software.amazon.jdbc.plugin.iam.IamAuthConnectionPlugin.level=FINEST
```
After enabling the driver logs you should see a log message starting with `"Generated new IAM token"` and the token looks something like: `{DBName}.{CLUSTER_ID}.{REGION}.rds.amazonaws.com/?DBUser= batch_user&...&X-Amz-Expires=900&%2F{REGION}%2Frds-db...`. Could you please confirm if the both of the `{REGION}` values match?

Could you please also add `iamRegion` to your connection parameters and let us know if the issue persists? i.e.
```
spring.datasource.hikari.data-source-properties.iamRegion: {REGION}
```

The driver uses the [default credentials provider](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html) during authentication, so you shouldn't need to configure a custom bean to retrieve Web Identity Token credentials. 
However, if the default credentials provider somehow isn't able to pick up AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN correctly from EKS, you could try configuring your own AWSCredentialsProvider, see [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/custom-configuration/AwsCredentialsConfiguration.md#aws-credentials-provider-configuration) for more information and an example.

**Comment by karenc-bq** [comment]
Hi @bdudra,

I wanted to check in and see if the PAM error is resolved.

If there are no further updates on this ticket in the next few days, we will close this ticket. However, if you require further assistance or if you have any other concerns, please feel free to comment on this issue or create a new issue.

Thank you!

**Comment by jpalomaki** [comment]
@bdudra @karenc-bq FWIW, in my case this very same error occurred, because I had mistakenly used the `cluster-<random string>` that appears in the database _hostname_ `some.cluster-abcdef123456.<region>.rds.amazonaws.com`, as cluster resource ID, within the necessary IAM policy `Resource` bit.

The _correct_ cluster resource ID is `DbClusterResourceId`, which one can retrieve using the AWS CLI like so:

```sh
aws --region <region> rds describe-db-clusters --db-cluster-identifier <cluster> | jq -r '.DBClusters[0].DbClusterResourceId'
```

See <https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html>
